---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

resources:
  - ns.yaml

  - api-server-deployment.yaml
  - api-server-externalsecret.yaml
  - api-server-ingressroute.yaml
  - api-server-service.yaml

  - playback-server-deployment.yaml
  - playback-server-externalsecret.yaml
  - playback-server-ingressroute.yaml
  - playback-server-service.yaml

  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingressroute.yaml

  - ted-irens-rtmp-encoder.yaml
