apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: musicloud

images:
  - name: postgres
    newName: postgres
    newTag: "18.1"

resources:
  - musicloud-ns.yaml
  - musicloud-postgres-deployment.yaml
  - musicloud-postgres-configmap.yaml
  - musicloud-postgres-pvc.yaml
  - musicloud-postgres-service.yaml
  - musicloud-postgres-migration-job.yaml
  - musicloud-server-deployment.yaml
  - musicloud-server-pvc.yaml
  - musicloud-server-service.yaml
  - musicloud-ignressroute.yaml
